/* tslint:disable */
/* eslint-disable */
/**
 * Volume API
 * API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@volumeapi.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

